# Matt Wang's zsh profile for general Linux/Unix
#
# Implementation notes:
#
# - Functions with name starts with '__' are considered 'private' and will be
#   unset at the end.
# - Functions with name starts with only one '_' are considered 'protected',
#   users can implement their own to override (via ~/.profiles.d).

# Example usage:
#   vif                       # pick files from ~/.fzf-file-list, send to vim
#   vif path [...]            # pick files from path..., send to vim
#   vif | cmd                 # pick files from ~/.fzf-file-list, send to cmd
#   vif path [...] | xargs .. # pick files from path..., send to xargs cmd
#   hg ls | vif               # pick files from commd output, send to vim
function vif {
    if type nvim >& /dev/null; then
        local arg=(--bind "enter:become(nvim -n {})")
    else
        local arg=(--bind "enter:become(vim -Xn -u ~/.vimrc {})")
    fi
    [[ -t 1 ]] || arg=()
    if [[ -t 0 ]]; then
        if (( $# > 0 )); then
            find "$@" -type f | fzf "${arg[@]}"
        else
            fzf "${arg[@]}" < ~/.fzf-file-list
        fi
    else
        fzf "${arg[@]}"
    fi
}

# "Protected" helper to decorate CWD used to setup PROMPT
function _source_control_cwd
{
    echo "%~"
}

# "Protected" helper to decorate source control information used to setup
# PROMPT, by default this only detect active git branch information. User can
# extend this to detect other version control system.
#
function _source_control_info
{
    if [[ $(git rev-parse --is-inside-work-tree 2>/dev/null) == true ]]; then
        _git_active_branch
    fi
}

function _git_active_branch
{
    local branch info age track

    branch=$(git symbolic-ref HEAD 2>/dev/null)
    branch=${branch#refs/heads/}
    info=$(git status -s 2>/dev/null)
    age=$(git log --pretty=format:'%cr' -1 refs/heads/$branch 2>/dev/null)
    track=$(git status -sb 2>/dev/null | sed -n 's/^##.*\[\(.*\)\].*/, \1/p')

    # XXX: $_DR and $_DG won't expand here
    if [[ -z $info ]]; then
        print -nP "%{\e[32m%}"
    elif [[ -z $(echo "$info" | grep -v '^??') ]]; then
        print -nP "%{\e[35m%}"
    else
        print -nP "%{\e[31m%}"
    fi

    print -n " ($branch) "  # No '-P' which does command expansion
    print -nP "%{\e[36m%}[${age}${track}]"
}

function __main
{
    local fn

    for fn in \
        __init_completion \
        __setup_path \
        __setup_shell_options \
        __setup_environments \
        __setup_aliases \
        __setup_completions \
        __setup_dir_colors \
        __setup_ssh_agent \
        __setup_prompt \
        __setup_custom_profiles \
    ; do
        $fn; unset -f $fn
    done
}

function __init_completion
{
    [[ ! -d ~/.zsh-completions ]] || fpath=(~/.zsh-completions/src $fpath)
    autoload -U compinit && compinit
}

function __setup_path
{
    local d

    for d in \
        /sbin \
        /usr/sbin \
        /bin \
        /usr/bin \
        /usr/local/bin \
        /opt/homebrew/bin \
        ~/.local/bin \
        ~/bin \
    ; do
        [[ -d $d ]] || continue

        # Remove the directory from PATH if it already exists
        PATH=":${PATH}:"
        PATH="${PATH//:${d}:/:}"
        PATH="${PATH#:}"
        PATH="${PATH%:}"

        # Prepend it to the front
        [[ -z "$PATH" ]] && PATH="$d" || PATH="$d:$PATH"
    done

    export PATH
}

function __setup_shell_options
{
    setopt shwordsplit                  # ARG="foo bar"; $ARG => "foo" "bar"
    setopt prompt_subst
    setopt interactive_comments
    setopt nocase_glob
    setopt nocase_match 2>/dev/null     # does not work for zsh < 4.3
    setopt extended_history
    setopt hist_expire_dups_first
    setopt hist_ignore_dups
    setopt hist_ignore_space
    setopt hist_find_no_dups
    setopt hist_verify
    setopt share_history
    setopt auto_pushd
    setopt pushd_ignore_dups
    unsetopt nomatch
    unsetopt correct
    bindkey -e                          # Reclaim C-a, C-e, C-r, M-., etc.
    ! test -t 0 || stty stop undef      # Make 'C-s' to do fwd-i-search
    bindkey "^U" backward-kill-line     # Keep the same behavior as in bash
}

function __setup_environments
{
    HISTFILE=~/.zhistory                # Prevent from ~/.zsh<tab> completion
    HISTSIZE=10000
    SAVEHIST=10000
    export EDITOR=vi
    ! type vim >& /dev/null || export EDITOR=vim
    ! type nvim >& /dev/null || export EDITOR=nvim

    # Locale (LC_*) matters for ls and sort on Linux, see also
    # www.gnu.org/software/coreutils/faq/#Sort-does-not-sort-in-normal-order_0021
    #
    [[ $OSTYPE != linux* ]] || export LC_COLLATE=C
}

function __setup_completions
{
    zstyle ':completion:*' menu yes select
    zstyle ':completion:*' users off
    zmodload zsh/complist
    bindkey -M menuselect '^M' .accept-line     # <Enter> only once to accept
    ZLE_REMOVE_SUFFIX_CHARS=                    # no space after, zshparam(1)
}

function __setup_aliases
{
    alias ..='cd ..'
    alias ...='cd ../..'
    alias ....='cd ../../..'
    alias .....='cd ../../../..'
    # Skip system wide vimrc to reduce startup time
    ! type vim >& /dev/null || alias vi='vim -Xn -u ~/.vimrc'
    ! type nvim >& /dev/null || alias vi='nvim'
    alias grep='grep --color=auto'
    alias ls="/bin/ls -F --color=auto"
    alias l="/bin/ls -lF --color=auto"

    case $OSTYPE in
        darwin*)
            export LSCOLORS="exgxfxfxcxdxdxbxbxcxbx"
            alias lsps='ps -ax -o user,pid,ppid,stime,tty,time,command | grep -vw grep | grep -i'
            ;;
        *)
            alias lsps='ps -auf | grep -vw grep | grep -i'
            ;;
    esac
}

function __setup_dir_colors
{
    local prog=dircolors

    [[ $OSTYPE != darwin* ]] || prog=gdircolors
    if type $prog >& /dev/null && [[ -f ~/.dircolors ]]; then
        eval $($prog -b ~/.dircolors)
    fi
}

function __setup_ssh_agent
{
    # Skip setting up ssh agent for non "Personal" profile. Expects user to use
    # different iTerm profiles "Work" and "Personal".
    [[ ${(U)ITERM_PROFILE} == "PERSONAL" ]] || [[ ${(U)TERM_PROFILE} == "PERSONAL" ]] || return 0

    # Assume personal environment from here.
    alias ssh='/usr/bin/ssh'
    alias ssh-add='/usr/bin/ssh-add'
    alias ssh-keygen='/usr/bin/ssh-keygen'
    alias sftp='/usr/bin/sftp'

    local key=~/.ssh/$USER.key
    local rc=~/.ssh-agent.rc
    local start_new=true

    [[ -f $key ]] || return 0
    if [[ -f $rc ]]; then
        source "$rc"
        /usr/bin/ssh-add -l >/dev/null 2>&1 && start_new=false
    fi

    if $start_new; then
        print -P "%{\e[31m%}Starting a new ssh-agent process...%{\e[0m%}" >&2
        rm -f ~/.ssh-agent.sock
        /usr/bin/ssh-agent -s -a ~/.ssh-agent.sock | sed '/^echo/d' > "$rc"
        source "$rc"
    fi

    /usr/bin/ssh-add -L | grep -q '^ssh' || /usr/bin/ssh-add "$key"
}

# Fancy PROMPT, prompt exit status of last command, currenet time, hostname,
# time, cwd, git status and branch, also prompt the '%' in reverse color when
# we have background jobs. NOTE: some symbols may not show correctly inside
# tmux, run tmux with option "-u" should fix it.
#
# Refs:
# - https://zsh.sourceforge.io/Doc/Release/Prompt-Expansion.html
# - https://zsh.sourceforge.io/Doc/Release/Zsh-Line-Editor.html#Special-Widgets
#
function __setup_prompt
{
    local distro

    if [[ $OSTYPE == darwin* ]]; then
        __OS_ICON=$'\uf179' # macOS
    else
        IFS='=' read -r _ distro < <(grep "^ID=" /etc/os-release 2>/dev/null)

        # Match the distro ID to a Nerd Font __OS_ICON
        # Ref: https://www.nerdfonts.com/cheat-sheet
        case "$distro" in
            debian) __OS_ICON=$'\uf306' ;;
            ubuntu) __OS_ICON=$'\uf31b' ;;
            *)      __OS_ICON=$'\uf31a' ;;  # Linux Tux
        esac
    fi

    PROMPT="%(?.%F{green}✔.%F{red}✘) %D{%T}%f "   # exit code and time
    PROMPT+="%F{yellow}\$(_source_control_cwd)%f" # yellow cwd
    PROMPT+="\$(_source_control_info)"            # vcs info
    PROMPT+=" %F{cyan}"$'⤾%f\n'                   # cyan wrap char+NL
    PROMPT+="%F{118}${__OS_ICON} %m%f"            # hilight OS icon, hostname
    PROMPT+=" %(1j.%S.)"                          # reverse bg job indicator
    PROMPT+="%B%#%s "                             # bold % or #, unreverse

    # Reset color when finished reading a cmd line
    function __zle_line_finish { echo -ne '\e[0m'; }
    zle -N zle-line-finish __zle_line_finish
}

# Load custom settings from ~/.profiles.d/*.sh, typical settings are
# docker-machine env, GOPATH, customized PATH etc.
#
function __setup_custom_profiles
{
    local p

    for p in ~/.profiles.d/*.sh(N); do
        source "$p"
    done
}

########################################################################
# Setup everything and unset the rest "private" functions
########################################################################

__main
unset -f __main

# vim:set et sts=4 sw=4 ft=zsh:
