# Matt Wang's bash profile for general Linux/Unix
#
# Suggestion: ln -sf .bashrc .bash_profile
#
# - Functions with name starts with '__' are considered 'private' and will be
#   unset at the end.
# - Functions with name starts with only one '_' are considered 'protected',
#   users can implement their own to override (via ~/.profiles.d).

# Example usage:
#   vif                       # pick files from ~/.fzf-file-list, send to vim
#   vif path [...]            # pick files from path..., send to vim
#   vif | cmd                 # pick files from ~/.fzf-file-list, send to cmd
#   vif path [...] | xargs .. # pick files from path..., send to xargs cmd
#   hg ls | vif               # pick files from commd output, send to vim
function vif
{
    if type nvim >& /dev/null; then
        local arg=(--bind "enter:become(nvim -n {})")
    else
        local arg=(--bind "enter:become(vim -Xn -u ~/.vimrc {})")
    fi
    [[ -t 1 ]] || arg=()
    if [[ -t 0 ]]; then
        if (( $# > 0 )); then
            find "$@" -type f | fzf "${arg[@]}"
        else
            fzf "${arg[@]}" < ~/.fzf-file-list
        fi
    else
        fzf "${arg[@]}"
    fi
}

# "Protected" helper to decorate CWD used to setup PS1
function _source_control_cwd
{
    [[ $PWD != ${HOME}* ]] || { echo ${PWD/$HOME/\~}; return 0; }
    echo $PWD
}

# "Protected" helper to decorate source control information used to setup
# PS1, by default this only detect active git branch information. User can
# extend this to detect other version control system.
#
function _source_control_info
{
    if [[ $(GIT_CEILING_DIRECTORIES=$HOME git rev-parse --is-inside-work-tree 2>/dev/null) == true ]]; then
        _git_active_branch
    fi
}

function _git_active_branch
{
    local branch info age track

    branch=$(git symbolic-ref HEAD 2>/dev/null)
    branch=${branch#refs/heads/}
    info=$(git status -s 2>/dev/null)
    age=$(git log --pretty=format:'%cr' -1 refs/heads/$branch 2>/dev/null)
    track=$(git status -sb 2>/dev/null | sed -n 's/^##.*\[\(.*\)\].*/, \1/p')

    # NOTE: have to use $'string' for ansi escape sequence here
    if [[ -z $info ]]; then
        echo -ne $'\e[32m'
    elif [[ -z $(echo "$info" | grep -v '^??') ]]; then
        echo -ne $'\e[35m'
    else
        echo -ne $'\e[31m'
    fi

    echo -n " ($branch) "
    echo -ne $'\e[36m'"[${age}${track}]"
}

function __main
{
    local fn

    [[ ! -f /etc/profile ]] || source /etc/profile
    [[ ! -f /etc/bashrc ]] || source /etc/bashrc
    unset PROMPT_COMMAND    # Let tmux manage it

    for fn in \
        __setup_path \
        __setup_shell_options \
        __setup_environments \
        __setup_aliases \
        __setup_completions \
        __setup_dir_colors \
        __setup_ssh_agent \
        __setup_prompt \
        __setup_custom_profiles \
    ; do
        $fn; unset -f $fn
    done
}

function __prepend_path
{
    [[ :$PATH: == *:${1:?}:* ]] || PATH=$1:$PATH
}

function __setup_path
{
    local d

    for d in \
        /sbin \
        /usr/sbin \
        /bin \
        /usr/bin \
        /usr/local/bin \
        /opt/homebrew/bin \
        ~/.local/bin \
        ~/bin \
    ; do
        [[ -d $d ]] || continue

        # Remove the directory from PATH if it already exists
        PATH=":${PATH}:"
        PATH="${PATH//:${d}:/:}"
        PATH="${PATH#:}"
        PATH="${PATH%:}"

        # Prepend it to the front
        [[ -z "$PATH" ]] && PATH="$d" || PATH="$d:$PATH"
    done

    export PATH
}

function __setup_shell_options
{
    bind 'set match-hidden-files off' >& /dev/null  # No tab-expand hidden files
    ! test -t 0 || stty stop undef >& /dev/null     # Make 'C-s' to do i-search
}

function __setup_environments
{
    HISTFILE=~/.bash_history     # In case switched from zsh temporally
    HISTSIZE=10000
    export EDITOR=vi
    ! type vim >& /dev/null || export EDITOR=vim
    ! type nvim >& /dev/null || export EDITOR=nvim

    # Locale (LC_*) matters for ls and sort on Linux, see also
    # www.gnu.org/software/coreutils/faq/#Sort-does-not-sort-in-normal-order_0021
    #
    [[ $OSTYPE != linux* ]] || export LC_COLLATE=C
}

function __setup_completions
{
    # git-completion.bash is installed by install.sh
    [[ ! -f ~/.git-completion.bash ]] || . ~/.git-completion.bash
    complete -A export unset
}

function __setup_aliases
{
    alias ..='cd ..'
    alias ...='cd ../..'
    alias ....='cd ../../..'
    alias .....='cd ../../../..'
    # Skip system wide vimrc to reduce startup time
    ! type vim >& /dev/null || alias vi='vim -Xn -u ~/.vimrc'
    ! type nvim >& /dev/null || alias vi='nvim'
    alias grep='grep --color=auto'
    alias ls="/bin/ls -F --color=auto"
    alias l="/bin/ls -lF --color=auto"

    case $OSTYPE in
        darwin*)
            export LSCOLORS="exgxfxfxcxdxdxbxbxcxbx"
            alias lsps='ps -ax -o user,pid,ppid,stime,tty,time,command | grep -vw grep | grep -i'
            ;;
        *)
            alias lsps='ps -auf | grep -vw grep | grep -i'
            ;;
    esac
}

function __setup_dir_colors
{
    local prog=dircolors

    [[ $OSTYPE != darwin* ]] || prog=gdircolors
    if type $prog >& /dev/null && [[ -f ~/.dircolors ]]; then
        eval $($prog -b ~/.dircolors)
    fi
}

function __setup_ssh_agent
{
    # NOTE for gMac: create a wrapper ~/bin/ssh (with symlink scp, sftp etc.)
    # as below to work better. See also ../ssh/config.sample.
    #
    # if echo "$*" | grep -qE "someCorpHostPattern"; then
    #     /usr/local/bin/$(basename $0) -o PubkeyAcceptedAlgorithms=ecdsa-sha2-nistp256-cert-v01@openssh.com "$@"
    # else
    #     /usr//bin/$(basename $0) -o PubkeyAcceptedAlgorithms=ssh-ed25519 "$@"
    # fi

    local key=~/.ssh/$USER.key

    [[ -f $key ]] || return 0
    # Modern OS should have a global ssh-agent set up already.
    ! /usr/bin/ssh-add -L | grep -q '^ssh' || return 0
    /usr/bin/ssh-add "$key" || {
        print -P "%F{red}Error adding $key; check \$SSH_AUTH_SOCK and ssh-agent process!%f" >&2
        return 1
    }
}

# Fancy PS1, prompt exit status of last command, currenet time, hostname, time,
# cwd, git status and branch, also prompt the '$' in reverse color when we have
# background jobs. '\[' and '\]' is to mark ansi colors to allow shell to
# calculate prompt string length correctly. NOTE: some symbols may not show
# correctly inside tmux, run tmux with option "-u" should fix it.
#
function __setup_prompt
{
    local _DR="\[\e[31m\]"        # red
    local _DG="\[\e[32m\]"        # green
    local _DY="\[\e[33m\]"        # yellow
    local _DB="\[\e[34m\]"        # blue
    local _DM="\[\e[35m\]"        # magenta
    local _DC="\[\e[36m\]"        # cyan
    local _RV="\[\e[7m\]"         # reverse
    local _NC="\[\e[0m\]"         # no color
    local _118="\[\e[38;5;118m\]" # color 118

    local distro

    if [[ $OSTYPE == darwin* ]]; then
        __OS_ICON=$'\uf179' # macOS
    else
        IFS='=' read -r _ distro < <(grep "^ID=" /etc/os-release 2>/dev/null)

        # Match the distro ID to a Nerd Font __OS_ICON
        # Ref: https://www.nerdfonts.com/cheat-sheet
        case "$distro" in
            debian) __OS_ICON=$'\uf306' ;;
            ubuntu) __OS_ICON=$'\uf31b' ;;
            *)      __OS_ICON=$'\uf31a' ;;  # Linux Tux
        esac
    fi

    PS1="\$([[ \$? == 0 ]] && echo '${_DG}✔' || echo '${_DR}✘') \t${_NC} "
                                                        # exit code and time
    PS1+="${_DY}\$(_source_control_cwd)${_NC}"          # yellow cwd
    PS1+="\$(_source_control_info)"                     # vcs info
    PS1+=" ${_DC}⤾\n"                                   # cyan wrap char, NL
    PS1+="${_118}${__OS_ICON}${_NC} ${HOSTNAME%%.*}"    # OS icon, hostname
    PS1+=" \$([[ -z \$(jobs) ]] || echo '$_RV')"        # reverse bg job
    PS1+='\[\e[1m\]\$'"${_NC} "                         # $ or #
}

# Load custom settings from ~/.profiles.d/*.sh, typical settings are
# docker-machine env, GOPATH, customized PATH etc.
#
function __setup_custom_profiles
{
    local p

    ls ~/.profiles.d/*.sh >& /dev/null || return 0

    for p in ~/.profiles.d/*.sh; do
        source "$p"
    done
}

########################################################################
# Setup everything and unset the rest "private" functions
########################################################################

__main
unset -f __main

# vim:set et sts=4 sw=4 ft=bash:
